---
- name: Uninstall masters
  ansible.builtin.include_tasks:
    file: uninstall_master.yml
  when: '"master" in group_names'

- name: Uninstall nodes
  ansible.builtin.include_tasks:
    file: uninstall_nodes.yml
  when: '"workers" in group_names'
