---
- name: Disable WIFI
  ansible.builtin.lineinfile:
    dest: /boot/firmware/config.txt
    line: 'dtoverlay=disable-wifi'
    state: present

- name: Disable Bluetooth
  ansible.builtin.lineinfile:
    dest: /boot/firmware/config.txt
    line: 'dtoverlay=disable-bt'
    state: present

- name: Set GPU memory
  ansible.builtin.lineinfile:
    dest: /boot/firmware/config.txt
    line: 'gpu_mem=16'
    state: present

- name: Enable container features (new)
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items: "{{ rpi_container_features }}"

- name: Run apt update
  ansible.builtin.apt:
    update_cache: true

- name: Run apt-get upgrade -y
  ansible.builtin.apt:
    upgrade: dist

- name: Run apt full-upgrade -y
  ansible.builtin.apt:
    upgrade: full

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
