---
- name: Create namespace "{{ apps.calico.namespace }}"
  become: false
  kubernetes.core.k8s:
    name: "{{ apps.calico.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

- name: Add calico chart repo
  become: false
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: "https://docs.tigera.io/calico/charts"
    force_update: true
  delegate_to: localhost

- name: Deploy Calico
  become: false
  ansible.builtin.shell: |
    helm dependency build &&
    helm template "{{ apps.calico.name }}" --include-crds --namespace "{{ apps.calico.namespace }}" . > resources/all.yaml &&
    kubectl apply --server-side=true --force-conflicts -n tigera-operator -k .
  args:
    chdir: "{{ playbook_dir }}/k3s-apps-install/files/homelab-pi-k3s/system/calico/"
  retries: 3
  delay: 5
  ignore_errors: true
  register: task_result
  until: task_result.rc == 0
  changed_when: true
  delegate_to: localhost

- name: Pause 5 minutes to deploy calico
  ansible.builtin.pause:
    minutes: 5

- name: Wait for calico pods to be running
  become: false
  ansible.builtin.command: kubectl get pods -n calico-system -o json
  register: kubectl_get_pods_calico
  until: kubectl_get_pods_calico.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 10
  delay: 60
  changed_when: true
  delegate_to: localhost

- name: Pause 5 minutes to deploy calico
  ansible.builtin.pause:
    minutes: 5
