---
- name: Git checkout homelab repo
  become: false
  ansible.builtin.git:
    repo: "{{ apps.homelab_repo }}"
    dest: "{{ playbook_dir }}/k3s-apps-install/files/homelab-pi-k3s"
    version: "{{ apps.branch_name }}"
    update: true
  delegate_to: localhost

- name: Git checkout argocd-homelab repo
  become: false
  ansible.builtin.git:
    repo: "{{ apps.argocd_homelab_repo }}"
    dest: "{{ playbook_dir }}/k3s-apps-install/files/argocd-homelab-pi-k3s"
    version: "{{ apps.branch_name }}"
    update: true
  delegate_to: localhost
