---
- name: Deploy k8tz
  become: false
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - '{{ playbook_dir }}/k3s-apps-install/files/argocd-homelab-pi-k3s/system/k8tz/project/k8tz.yaml'
    - '{{ playbook_dir }}/k3s-apps-install/files/argocd-homelab-pi-k3s/system/k8tz/application/k8tz.yaml'
  delegate_to: localhost

- name: Pause 1 minutes to deploy k8tz
  ansible.builtin.pause:
    minutes: 1

- name: Wait for k8tz pods to be running
  become: false
  ansible.builtin.command: kubectl get pods -n k8tz -o json
  register: kubectl_get_pods_k8tz
  until: kubectl_get_pods_k8tz.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 10
  delay: 30
  changed_when: true
  delegate_to: localhost
