---
- name: Deploy nfs-provisioner
  become: false
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - '{{ playbook_dir }}/k3s-apps-install/files/argocd-homelab-pi-k3s/system/nfs-provisioner/project/nfs-provisioner.yaml'
    - '{{ playbook_dir }}/k3s-apps-install/files/argocd-homelab-pi-k3s/system/nfs-provisioner/application/nfs-provisioner.yaml'
  delegate_to: localhost

- name: Pause 30 seconds to deploy nfs-provisioner
  ansible.builtin.pause:
    seconds: 30

- name: Wait for nfs-provisioner pods to be running
  become: false
  ansible.builtin.command: kubectl get pods -n nfs-provisioner -o json
  register: kubectl_get_pods_nfs_provisioner
  until: kubectl_get_pods_nfs_provisioner.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 10
  delay: 30
  changed_when: true
  delegate_to: localhost
